### ISSUE TITLE
Applying patch fails for symfony/dependency-injection 6.2.x

### ISSUE THREAD

**Issue by eliashaeussler** [symplify/vendor-patch-files#1]
Hi @TomasVotruba,

I tried setting up `rectorphp/rector-src` and cannot get it running because of the following exception during `composer update`:

```
  - Applying patches for symfony/dependency-injection
    https://raw.githubusercontent.com/symplify/vendor-patch-files/main/patches/generic-php-config-loader.patch (0)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://raw.githubusercontent.com/symplify/vendor-patch-files/main/patches/generic-php-config-loader.patch

In Patches.php line 326:
                                                                                                                                      
  Cannot apply patch 0 (https://raw.githubusercontent.com/symplify/vendor-patch-files/main/patches/generic-php-config-loader.patch)!  
```

I found out that it cannot be applied since the `Loader/PhpFileLoader.php` file in `symfony/dependency-injection` changed with the 6.2.0 release (see symfony/symfony#47906 for reference).

When updating dependencies with `composer update --with=symfony/dependency-injection:6.1.8` it works as expected.

**Comment by TomasVotruba** [comment]
Hi, the rector/rector-src should never be used as a dependency, as it's dev repository.
Instead, go for rector/rector repository

**Comment by eliashaeussler** [comment]
Sorry, the initial description was a bit unclear.

I was setting up rector-src while contributing to rectorphp/rector-src#3174. The contribution guide says an initial `composer update` is required which led to mentioned error. Since this error came from a patch provided by this library, I thought it might be useful to share my experience.

**Comment by TomasVotruba** [comment]
The Symfony 6.1 is locked there: https://github.com/rectorphp/rector-src/blob/b23e1fb2ea7795a7f7bb3f6232e4fa82aa26b199/composer.json#L34

I don't think the Symfony 6.2 could get in there
